#        git clone https://github.com/sphinx-doc/sphinx
#        cd sphinx
#        pip3 install .
name: deploy

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Clone pre repositories
      run: |
        cd ..
        git clone -b push https://github.com/nickcafferry/heyujin-foreverlove.git manim
        cd manim
    
    - name: Install setuptools
      run: |
        cd ..
        pip3 install --upgrade pip
        wget --no-check-certificate  https://pypi.python.org/packages/source/s/setuptools/setuptools-19.6.tar.gz#md5=c607dd118eae682c44ed146367a17e26
        tar -zxvf setuptools-19.6.tar.gz
        cd setuptools-19.6
        sudo python3 setup.py build
        sudo python3 setup.py install
    
    - name: Install sphinx
      run: |
        cd ..
        git clone https://github.com/sphinx-doc/sphinx
        cd sphinx
        pip3 install -U Sphinx 
        pip3 install sphinx_rtd_theme
        pip3 install jieba
    
    - name: Build document with Sphinx
      run: |
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/heyujin-foreverlove/manim"
        make html
        cd build/html
        echo "heyujin-foreverlove.ink" > CNAME
        
    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/html
